### ISSUE TITLE
remove logger dependency

### ISSUE THREAD

**Issue by stokito** [benjaminch/openrtb-pricers#12]
Hi, thank you for you lib.
 I trying to keep dependencies as small as possible but the lib uses some YetAnotherLogger.
I don't feel like here it's needed at all. Is it possible to remove it?

**Comment by stokito** [comment]
I created a PR that removes it. For a users it should be enough just to have an error. Internal details are useful only for debug of the library itself

**Comment by benjaminch** [comment]
Hello !

Yes makes sense to me, let move forward ;)
